- name: List SMB shares via SSH
  hosts: sd1isilon001.na.am.lilly.com
  gather_facts: no
  tasks:
    - name: Run isi smb shares list
      command: isi smb shares list
      register: smb_output

    - name: Show shares
      debug:
        var: smb_output.stdout_lines
